name: regfans
channels:
  - conda-forge
dependencies:
  - python >=3.11
  - numpy
  - python-flint
  - ppl
  - pytest
  - scipy
  - pip
  - pip:
    - networkx
    - ortools
    - pplpy
    - triangulumancer
